### ISSUE TITLE
History recorded after created, not respecting recordHistory definition

### ISSUE THREAD

**Issue by reefki** [asantibanez/laravel-eloquent-state-machines#1]
Thanks for this neat package!

I don't know if you are intended to make it this way but I found that history gets recorded when a model created even though I have `stateHistory` returns `false`.

When I see the boot method of `HasStateMachine` class, it just records the history when listening to the model `created` event without checking `stateHistory` definition.

**Edit**
Just an idea, I think it would be better if it also records the user who performed the transition using `user_id` column. I'll submit a PR if you think it's a good idea

**Comment by asantibanez** [comment]
Hi @reefki ! Thank you! 😊 

Yes. I've noticed that behavior. Fixing it soon.

In regards of `user_id`, what would be the expected value for it? `auth()->id()`? What happens if there is no `auth()` when applying the transition eg transitioning between states in a job?

**Comment by asantibanez** [comment]
Fixed @reefki 

Checkout v1.0.1 👍

**Comment by reefki** [comment]
@asantibanez Thank you for your quick response and the fix!

Yes, when the `auth()->user()` found, associate the record with the currently logged-in user otherwise just leave it `null`.

I think this would be useful for apps that allow multiple users to manage certain models, this way we can know who changed the status. In case the value is `null` that we can easily tell that no one is responsible but the application's internal system. In the frontend we can use something like `optional($history->user->name) ?? __('System')`.

**Comment by asantibanez** [comment]
@reefki feedback welcomed on #4 . Let me know what you think.
