### ISSUE TITLE
Error : Class 'Str' not found

### ISSUE THREAD

**Issue by j-dohnalek** [asantibanez/laravel-eloquent-state-machines#10]
**Describe the bug**

Laravel 6.20.8
PHP 7.3.25

Running one of our tests produces exception `Error : Class 'Str' not found`, the test uses one of the classes from your package.

vendor/asantibanez/laravel-eloquent-state-machines/src/Traits/HasStateMachines.php:31

```php
$camelField = Str::of($field)->camel();
```

If I import `Illuminate\Support\Str` another exception is thrown for `BadMethodCall` that `Str` does not have method `of`

**Solution Ideas**

Line 11

```php
use Illuminate\Support\Str;
```

Line 31

```php
$camelField = Str::camel($field);
```

Line 38

```php
$studlyField = Str::studly($field);
```

After these changes our tests are passing

**Comment by asantibanez** [comment]
Hey @j-dohnalek 

Just fixed this! Check out https://github.com/asantibanez/laravel-eloquent-state-machines/releases/tag/v2.3.0
