### ISSUE TITLE
Custom properties available in transition hooks

### ISSUE THREAD

**Issue by edwinvdpol** [asantibanez/laravel-eloquent-state-machines#20]
### Summary
I would like the custom properties to be available in the before- and after transition hooks.
This way, you can provide extra information which you can process in the hooks, for example update a date field of a model.

### Proposal
```php
// src/StateMachines/StateMachine.php#114

collect($beforeTransitionHooks)
    ->each(function ($callable) use ($to, $customProperties) {
        $callable($to, $this->model, $customProperties);
    });

// src/StateMachines/StateMachine.php#134

collect($afterTransitionHooks)
    ->each(function ($callable) use ($from, $customProperties) {
        $callable($from, $this->model, $customProperties);
    });
```

### Additional Notes
If you'd like, I can create a PR. If you have another solution, let me know ;-)

**Comment by asantibanez** [comment]
Sounds good @edwinvdpol . Haven't thought about this use case. Send your PR for review. 👍
