### ISSUE TITLE
Record responsible user on model creation

### ISSUE THREAD

**Issue by j-dohnalek** [asantibanez/laravel-eloquent-state-machines#6]
Thanks for the great package.

### Summary
What's the new feature about? What should it do?

Ability to record responsible user for the default state.

### Proposal
How should it work? API ideas?

If responsible user is available, record it when the model is created.

### Additional Info

![image](https://user-images.githubusercontent.com/6439903/102350121-51843900-3f9c-11eb-8881-2610111204b2.png)

```php
$responsible = \Auth::user() ?? null;
$model->recordState($field, null, $currentState, [], $responsible);
```

**Comment by asantibanez** [comment]
Closed via #7 

Thank you! 🤗
